terms_jp_en = {
    "ジム": "Jim", 
    "ボトル": "Bottle",
    "ゴーニーガロン": "52 Galon",
    "ゴーミーガロン": "52 Galon",
    "ゴーニー": "52",
    "合二": "52",
    "シャーカー": "SharpMarker",
    "シャープマーカー": "SharpMarker",
    "クワットホッパー": "Quad",
    "クワット": "Quad",
    "ラクト": "LACT-450",
    "トライストリング":"TriSlinger",
    "トライストリンガー":"TriSlinger",
    "フィンセット": "Vincent",
    "フィンセント": "Vincent",
    "ラピエリ": "RapidElite",
    "ラピ": "RapidGun",
    "リッター": "4K",
    "9番": "Suction Bomb",
    "カリランク": "KaniTank",
    "カニタンク": "KaniTank",
    "トルネデー": "Tornado",
    "トルネ": "Tornado",
    "トルネード": "Tornado",
    "大仏": "Daibuzi",
    "たいぶつ": "Daibuzi",
    "ジジイ": "GG",
    "ホコ": "Hogo",
    "ヤグラ": "Tower",
    "やがら": "Tower",
    "パワー": " Power",
    "ねっぴー": "Neppy",
    "ラピッド": "RapidGun",
    "アサリ": "Clam",
    "イカニンジャ": "SquidNinjya",
    "イカ速": "SquidSpeed",
    "スシ": "Sushi",
    "スプラシューター": "Sushi",
    "スシコラ": "SushiCola",
    "ロング": "LongBlaster",
    "ウルトラショット": "RPG",
    "ウルショ": "RPG",
    "クイックボム": "QuickBomb",
    "クイボ": "QuickBomb",
    "メガホン": "Laser",
    "ノヴァ": "Nova",
    "バリア": "Barrier",
    "エリア": "Area",
    "パブロ": "Pablo",
    "マニュ": "Maniu",
    "バケット": "Bucket",
    "ばけっず": "Bucket",
    "バケ": "Bucket",
    "ヒッセン": "BlueBucket",
    "立ち回り": "Tachimawari",
    "ムニエル": "PowerStation",
    "アラマキ": "Castle",
    "ドンブラコ": "Ship",
    "シェケナダム": "Dam",
    "ダム": "Dam",
    "すじこ": "Highway",
    "トキシラズ": "Factory",
    "ジムワイパー": "Jim",
    "デコイ": "Fireworks",
    "ロボム": "RobotBomb",
    "ロボットボム": "RobotBomb",
    "ヒラメ": "flounder",
    "イグザミナー": "Examiner",
    "トーピード": "FishBomb",
    "キンメダイ": "ArtMuseum",
    "たけ": "Bamboo",
    "チャー": "Cha",
    "カバー": "Cover",
    "カバ": "Cover",
    "ダイナモ": "Dynamo",
    "ダイナモローラー": "Dynamo",
    "バイトチームコンテスト": "TeamContest",
    "編成": "Hensei",
    "ザコシャケ": "Zako",
    "雑魚": "Zako",
    "塗り": "Nuri",
    "ヒカリバエ": "Hikari",
    "ハシラ": "Column",
    "デュアルスイーパー": "RedDoubleGun",
    "デュアル": "RedDoubleGun",
    "ダイバー": "Diver",
    "モグラ": "Mole",
    "カタパッド": "Rubbish",
    "カタパ": "Rubbish",
    "コウモリ": "Bat",
    "タマヒロイ": "Thief",
    "ヘビ": "Snake",
    "ナベブタ": "Nabebuta",
    "カゴ": "Kago",
    "コジャケ": "SmallFish",
    "シャケ": "MediumFish",
    "ドスコイ": "BigFish",
    "爆風": "BombWind",
    "テッパン": "Tepan",
    "バクダン": "BombFish",
    "ジェットパック": "Jetpack",
    "ジェパ": "Jetpack",
    "スペシャル": "Special",
    "テッキュウ": "Tekiu",

    # Add more terms as needed
}

terms_en_cn = {
    "Jim": "电锯", 
    "Bottle": "香槟",
    "52 Galon": "52加仑",
    "SharpMarker": "针管",
    "TriSlinger":"三发猎鱼弓",
    "Quad": "气垫",
    "Vincent": "文森",
    "RapidElite": "精英爆破枪",
    "Suction Bomb": "吸盘炸弹",
    "KaniTank": "螃蟹",
    "Tornado": "龙卷风",
    "Daibuzi": "对物攻击提升",
    "Hogo": "鱼虎",
    "Tower": "塔台",
    "Neppy": "奶啤",
    "RapidGun": "快速爆破枪",
    "Clam": "蛤蜊",
    "SquidNinjya": "隐游",
    "SquidSpeed": "游速",
    "Sushi": "小绿",
    "Sushicola": "贴牌小绿",
    "LongBlaster": "长热",
    "QuickBomb": "水球",
    "Laser": "镭射",
    "Nova": "白泡",
    "Barrier": "防护罩",
    "Area": "区域",
    "Pablo": "巴勃罗",
    "Maniu": "绿双",
    "Bucket": "红桶",
    "BlueBucket": "绿桶",
    "Tachimawari": "立回",
    "Castle": "新卷堡",
    "PowerStation": "发电所",
    "Ship": "破船",
    "Dam": "鲑坝",
    "Highway": "生筋子",
    "Factory": "工房",
    "Fireworks": "诱饵烟花",
    "RobotBomb": "小鸡雷",
    "Flounder": "比目鱼住宅区",
    "Examiner": "审查者",
    "FishBomb": "鱼雷",
    "ArtMuseum": "金眼鲷美术馆",
    "Bamboo": "竹狙",
    "Cha": "狙击枪",
    "Cover": "掩护",
    "Dynamo": "重刷",
    "TeamContest": "团队打工竞赛",
    "Hensei": "编成",
    "Zako": "杂鱼",
    "Nuri": "涂地",
    "Hikari": "光蝇",
    "Column": "柱鱼",
    "RedDoubleGun": "红双",
    "Diver": "潜水鱼",
    "Mole": "鼹鼠鱼",
    "Rubbish": "垫肩飞鱼",
    "Bat": "蝙蝠鱼",
    "Thief": "偷蛋鱼",
    "Snake": "蛇鱼",
    "Nabebuta": "锅盖鱼",
    "Kago": "蛋框",
    "SmallFish": "小鲑鱼",
    "MediumFish": "鲑鱼",
    "BigFish": "大胖鱼",
    "BombWind": "爆风",
    "Tepan": "铁板鱼",
    "BombFish": "绿帽",
    "Jetpack": "喷气背包",
    "Special": "大招",
    "Tekiu": "铁球鱼",

    
}
