terms_jp_en = {
    "ジム": "Jim", 
    "ボトル": "Bottle",
    "ゴーニーガロン": "52 Galon",
    "ゴーミーガロン": "52 Galon",
    "ゴーニー": "52",
    "合二": "52",
    "シャーカー": "SharpMarker",
    "シャープマーカー": "SharpMarker",
    "クワットホッパー": "Quad",
    "クワット": "Quad",
    "ラクト": "LACT-450",
    "トライストリング":"TriSlinger",
    "トライストリンガー":"TriSlinger",
    "フィンセット": "Vincent",
    "ラピエリ": "RapidGun",
    "リッター": "4K",
    "9番": "Suction Bomb",
    "カリランク": "KaniTank",
    "トルネデー": "Tornado",
    "トルネ": "Tornado",
    "大仏": "Daibuzi",
    "ジジイ": "GG",
    "ホコ": "Hogo",
    "ヤグラ": "Tower",
    "やがら": "Tower",
    "パワー": " Power",
    "ねっぴー": "Neppy",

    # Add more terms as needed
}

terms_en_cn = {
    "Jim": "电锯", 
    "Bottle": "香槟",
    "52 Galon": "52加仑",
    "SharpMarker": "针管",
    "TriSlinger":"三发猎鱼弓",
    "Quad": "气垫",
    "Vincent": "文森",
    "RapidGun": "快速爆破",
    "Suction Bomb": "吸盘炸弹",
    "KaniTank": "螃蟹",
    "Tornado": "龙卷风",
    "Daibuzi": "对物攻击提升",
    "Hogo": "鱼虎",
    "Tower": "塔台",
    "Neppy": "奶啤",

}