terms_jp_en = {
    "ジム": "Jim", 
    "ボトル": "Bottle",
    "ゴーニーガロン": "52 Galon",
    "ゴーミーガロン": "52 Galon",
    "ゴーニー": "52",
    "合二": "52",
    "シャーカー": "SharpMarker",
    "シャープマーカー": "SharpMarker",
    "クワットホッパー": "Quad",
    "クワット": "Quad",
    "ラクト": "LACT-450",
    "トライストリング":"TriSlinger",
    "トライストリンガー":"TriSlinger",
    "フィンセット": "Vincent",
    "フィンセント": "Vincent",
    "ラピエリ": "RapidElite",
    "ラピ": "RapidGun",
    "リッター": "4K",
    "9番": "Suction Bomb",
    "カリランク": "KaniTank",
    "カニタンク": "KaniTank",
    "トルネデー": "Tornado",
    "トルネ": "Tornado",
    "トルネード": "Tornado",
    "大仏": "Daibuzi",
    "たいぶつ": "Daibuzi",
    "ジジイ": "GG",
    "ホコ": "Hogo",
    "ヤグラ": "Tower",
    "やがら": "Tower",
    "パワー": " Power",
    "ねっぴー": "Neppy",
    "ラピッド": "RapidGun",
    "アサリ": "Clam",
    "イカニンジャ": "SquidNinjya",
    "イカ速": "SquidSpeed",
    "スシ": "Sushi",
    "スプラシューター": "Sushi",
    "スシコラ": "SushiCola",
    "ロング": "LongBlaster",
    "ウルトラショット": "RPG",
    "ウルショ": "RPG",
    "クイックボム": "QuickBomb",
    "クイボ": "QuickBomb",
    "メガホン": "Laser",
    "ノヴァ": "Nova",
    "バリア": "Barrier",
    "エリア": "Area",
    "パブロ": "Pablo",
    "マニュ": "Maniu",
    "バケット": "Bucket",
    "ばけっず": "Bucket",
    "バケ": "Bucket",
    "ヒッセン": "BlueBucket",
    "立ち回り": "Tachimawari",
    "ムニエル": "PowerStation",
    "アラマキ": "Castle",
    "ドンブラコ": "Ship",
    "シェケナダム": "Dam",
    "ダム": "Dam",
    "すじこ": "Highway",
    "トキシラズ": "Factory",
    "ジムワイパー": "Jim",
    "デコイ": "Fireworks",
    "ロボム": "RobotBomb",
    "ロボットボム": "RobotBomb",
    "ヒラメ": "flounder",
    "イグザミナー": "Examiner",
    "トーピード": "FishBomb",
    "キンメダイ": "ArtMuseum",
    "たけ": "Bamboo",
    "チャー": "Cha",
    "カバー": "Cover",
    "カバ": "Cover",



    # Add more terms as needed
}

terms_en_cn = {
    "Jim": "电锯", 
    "Bottle": "香槟",
    "52 Galon": "52加仑",
    "SharpMarker": "针管",
    "TriSlinger":"三发猎鱼弓",
    "Quad": "气垫",
    "Vincent": "文森",
    "RapidElite": "精英爆破枪",
    "Suction Bomb": "吸盘炸弹",
    "KaniTank": "螃蟹",
    "Tornado": "龙卷风",
    "Daibuzi": "对物攻击提升",
    "Hogo": "鱼虎",
    "Tower": "塔台",
    "Neppy": "奶啤",
    "RapidGun": "快速爆破枪",
    "Clam": "蛤蜊",
    "SquidNinjya": "隐游",
    "SquidSpeed": "游速",
    "Sushi": "小绿",
    "Sushicola": "贴牌小绿",
    "LongBlaster": "长热",
    "QuickBomb": "水球",
    "Laser": "镭射",
    "Nova": "白泡",
    "Barrier": "防护罩",
    "Area": "区域",
    "Pablo": "巴勃罗",
    "Maniu": "绿双",
    "Bucket": "红桶",
    "BlueBucket": "绿桶",
    "Tachimawari": "立回",
    "Castle": "新卷堡",
    "PowerStation": "发电所",
    "Ship": "破船",
    "Dam": "鲑坝",
    "Highway": "生筋子",
    "Factory": "工房",
    "Fireworks": "诱饵烟花",
    "RobotBomb": "小鸡雷",
    "Flounder": "比目鱼住宅区",
    "Examiner": "审查者",
    "FishBomb": "鱼雷",
    "ArtMuseum": "金眼鲷美术馆",
    "Bamboo": "竹狙",
    "Cha": "狙击枪",
    "Cover": "掩护",



}
